### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by YoannKermaidic** [dune-lardon/lardon#13]
- [x] mask signal in pedestals (induction / collection) -> Yoann
- [x] #21
- [ ] differentiating reconstruction process for Top and Bottom electronics.
- [ ] #15
- [ ] #16
- [x] output file at noise level / t2d level -> Laura
- [ ] estimate impact of noise filters on (x,y,z) and E uncertainties -> Long term
- [ ] check dead CRP regions (Dominique wish) -> Laura
- [ ] Investigate ROI rms threshold per view/signal type/electronics --> Yoann
- [ ] Investigate noise : Jura/saleve ? strip capacitance ? FFT per strip length ? ... --> Thibaut et al
- [ ] Understand the shape of induction signal --> Everyone !
- [ ] Benchmarking plots (lardon itself ; with larsoft) -> Yoann (ongoing work with Thomas)
- [ ] Improve comments in the code -> Everyone !
- [ ] Make `hit_finder.py` loops numba-compatible and test speed -> Yoann
- [ ] Try to speed-up high frequency noise with recursive filters in numba -> TBD.

**Comment by olantwin** [comment]
Might have a look at the two optimisation bullet points + adapt the decoder to read the 50L data.

**Comment by olantwin** [comment]
Thanks for the list!
